### PR TITLE
Issue 14 add ci build and documentation for critical

### LINKED ISSUE #14: critical 1.0.0 upgrade introduced (undocumented?) breaking change / dependency on puppeteer (Headless Chrome)
as [observed in the webpack v4 upgrade issue](https://github.com/anthonygore/html-critical-webpack-plugin/issues/9#issuecomment-377991102), it seems that as part of the [1.0.0 release of critical](https://github.com/addyosmani/critical/releases/tag/v1.0.0) the package migrated to using Headless Chrome from PhantomJS, which means all build environments  (local, CI, etc) have to have support for [puppeteer](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) or else builds will break silently.

There's not much for the plugin team to do per se as it will be incumbent on consumers to provide the "correct" build time environment, but I think a couple things could be done to prevent future regressions / awareness
1. introducing some basic CI into the project that tests (and fails, ideally) the build when `critical` itself fails
1. Add some documentation in the README about the **puppeteer** dependency

### PR DESCRIPTION
**Pull request by thescientist13**
resolves #14 

### Overview
This PR aims to document this project's dependency on [**critical**](https://www.npmjs.com/package/critical) which was [updated recently](https://github.com/addyosmani/critical/releases/tag/v1.0.0) to use [Headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) (via [**puppeteer**](https://github.com/GoogleChrome/puppeteer)) (instead of PhantomJS).  

This now requires consuming build time environments have support to run [Headless Chrome](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md).

### Changes
1. Added a CircleCi config file (using an image that supports Headless Chrome)
1. Added consumer documentation around Headless Chrome / puppeteer
1. Fixed some tests

_**Notes:**_
#### Before
[Ran the build](https://circleci.com/gh/anthonygore/html-critical-webpack-plugin/6) once using a "stock" Docker image, **circleci/node:8.9.4** to help demonstrate the issue of the build needed Headless Chrome packages.

We can see that when the tests run, which invoke **HtmlCriticalWebpackPlugin** and ultimately **critical**, we get a node error attributed to **puppeteer** under the "Run Tests" section.  (ideally this should cause the build to fail though but seems to be a [mocha / node related issue](https://github.com/mochajs/mocha/issues/2640))
screen shot 2018-05-09 at 5 19 51 pm

#### After
Then updated the PR to use a [Docker image](https://hub.docker.com/r/thegreenhouse/nodejs-dev/) I put together specifically with the goal of being able to [run Headless Chrome for NodeJS projects](https://github.com/thegreenhouseio/docker-nodejs-dev/blob/master/Dockerfile), and now we get the [test results](https://circleci.com/gh/anthonygore/html-critical-webpack-plugin/15) we're looking for!  ✅ 
screen shot 2018-05-09 at 6 30 44 pm

My Docker image is pretty straightforward
```shell
FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y curl vim git bzip2 ssh

# install HeadlessChrome X11 packages
# https://github.com/Quramy/puppeteer-example#with-docker-based-ci-services
RUN apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
      libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
      libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
      libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
      ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

# install NodeJS LTS
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

# install latest yarn@^1.0.0
# use yarn to install npm \_(ツ)_/¯
# https://stackoverflow.com/questions/44269086/how-to-upgrade-npm-to-npm5-on-the-latest-node-docker-image
RUN npm install -g yarn@^1.0.0

# upgrade to latest release of npm@^5.0.0
RUN yarn global add npm@^5.0.0

# environment info
RUN node -v
RUN npm -v
RUN yarn -v
```

### TODO
1. [ ] ~~try and get CircleCI to fail in the "before" case where the build should fail because Headless Chrome wasn't started~~ This seems out of scope for this PR, and should be tracked in the **mocha** issue tracker
1. [x] Update this ticket with results, screenshots, links to the builds, etc
1. [x] Should add developer documentation around using Docker

### CODE REVIEW

**Comment by thescientist13** [comment]
Hmm, this is still building against my fork and not from here
https://circleci.com/gh/anthonygore/html-critical-webpack-plugin

**Comment by thescientist13** [comment]
This [support article](https://support.circleci.com/hc/en-us/articles/115015447187-Commits-not-building-after-username-project-or-repo-renamed) suggested deleting any existing webhooks (which I had on my repo) and setting up the project again.

@anthonygore 
Do you mind doing me a favor and deleting the project you made in CircleCI and setting up again?  I think that should help just to be sure.

**Comment by anthonygore** [comment]
Done

**Comment by thescientist13** [comment]
thanks @anthonygore .  still doesn't seem to be building.  can you confirm a couple things
- [ ] a new Webhook was added to this project's GitHub setting's from CircleCI (should only be 1)
- [ ] the build forked pull requests setting is set to "on"
- [ ] the free and open source setting is set to "on"

thanks!

**Comment by anthonygore** [comment]
Hi Owen. All those settings are correct. I just created a branch and pull request to test it and triggered a build, so I'm not sure what the cause of your troubles are!

**Comment by thescientist13** [comment]
AH HA!  There we go 😊 .  I still had a project configuration for my fork, even though it wasn't building, but then I deleted it and 💥 !  

@anthonygore 
Will update the description and let you know when everything is ready to review .

**Comment by thescientist13** [comment]
@anthonygore 
All set for you to review! 👍

**Comment by anthonygore** [comment]
Brilliant! Thanks, Owen. I'll go through this shortly.

**Pull request merged**
